### ISSUE TITLE
 no powermeter defined!

### ISSUE THREAD

**Issue by tstrempel1980** [tomquist/b2500-meter#9]
Hallo zusammen,
ich habe die config.ini Datei erzeigt und den General Eintrag sowie den shelly_3em eingetragen.
trotzdem sagt er das er den Powermeter nicht findet?
Debian 10 mit iobroker auf einem Rasppbery b2
iobroker@debian:~/b2500-meter-main$ python3
Python 3.9.2 (default, Feb 28 2021, 17:03:44)
```
[GENERAL]
# By default, the script will sum the power values of all phases and report them as a single value on phase 1. To disable this behavior, add the following configuration to the `config.ini` file
DISABLE_SUM_PHASES = False
# Setting this to true, disables the powermeter test at the beginning of the script.
SKIP_POWERMETER_TEST = False
# By default, the script sends an absolute value of the measured power. This seems to be necessary for the storage system, since it can't handle negative values (results in an integer overflow). Set this to true to clamp the values to 0 instead of sending the absolute value.
DISABLE_ABSOLUTE_VALUES = False
# Sets the interval at which the script sends new power values to the B2500 in seconds. The original Smart Meter sends new values every second.
POLL_INTERVAL = 1

[SHELLY_3EM]
TYPE = 3EM
IP = 192.168.178.250
USER = shelly3em
PASS = #########
METER_INDEX = meter1
```
Fehlermeldung:
iobroker@debian:~/b2500-meter-main$ pipenv run python3 main.py
Traceback (most recent call last):
  File "/home/iobroker/b2500-meter-main/main.py", line 109, in <module>
    main()
  File "/home/iobroker/b2500-meter-main/main.py", line 51, in main
    powermeter = create_powermeter(cfg)
  File "/home/iobroker/b2500-meter-main/config/config_loader.py", line 62, in create_powermeter
    raise Exception("Error: no powermeter defined!")
Exception: Error: no powermeter defined!

Unter Windows11 mit python...
Python 3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024

C:\b2500-meter-main>pipenv run python main.py
Testing powermeter configuration...
Error: Expecting value: line 1 column 1 (char 0)

**Comment by tomquist** [comment]
Das Problem ist, dass es die section `[SHELLY_3EM]` nicht gibt. Versuche stattdessen bitte `[SHELLY]`.
